name: Deploy to server
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH With Ec2 instance
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Making git safe directory
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.61.151.146 << 'EOF'
          git config --global --add safe.directory /var/www/html/Apache
          EOF

      - name: Deploy To Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.61.151.146 << 'EOF'
          set -e
          set -x  # Enable debugging to show commands being executed

          # Navigate to the project directory
          cd /var/www/html/Apache/

          # Save the current commit hash for rollback
          LAST_COMMIT=$(git rev-parse HEAD)
          echo $LAST_COMMIT > /home/ubuntu/last_commit

          # Check the status of the repository and pull the latest changes
          git status
          git checkout main
          git pull origin main || {
            echo "Deployment failed due to git pull error"
            git reset --hard $(cat /home/ubuntu/last_commit)
            exit 1
          }

          # Set ownership for the project directory
          chown -R www-data:www-data /var/www/html/Apache

          echo "Deployment successful"
          EOF
