name: Deploy CRM to APACHE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH for EC2
      uses: webfactory/ssh-agent@v0.6.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set git safe dir
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.61.151.146 <<'EOF'
          git config --global --add safe.directory /var/www/html/Apache
        EOF

    - name: Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.61.151.146 <<'EOF'
          set -e

          # Save the current state
          cd /var/www/html/Apache
          LAST_COMMIT=$(git rev-parse HEAD)
          echo $LAST_COMMIT > /home/ubuntu/last_commit

          # Try deploying
          git checkout main
          git pull origin main || {
            echo "Deployment failed, rolling back ...";
            git reset --hard $(cat /home/ubuntu/last_commit);
            exit 1;
          }

          # Change ownership after deployment
          #chown -R www-data:www-data /var/www/html/Apache
        EOF

